apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gh-proxy.com/https://github.com/jory-callan/gitops-base
    targetRevision: HEAD
    path: apps/victoria-logs
  destination:
    server: https://kubernetes.default.svc
    namespace: victorialogs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
