apiVersion: v1
kind: Secret
metadata:
  name: minio-ak-public-read
  namespace: minio
  labels:
    app: minio
    minio-ak-type: user
type: Opaque
stringData:
  accesskey: public-read-user
  secretkey: prd-s3k-5a8c2e7d4b1f
  bucket: public-read
  endpoint: http://minio.minio.svc.cluster.local:80
