apiVersion: v1
kind: Secret
metadata:
  name: minio-ak-public
  namespace: minio
  labels:
    app: minio
    minio-ak-type: user
type: Opaque
stringData:
  accesskey: public-rw-user
  secretkey: pr-s3k-3b6f9a2c7d1e
  bucket: public
  endpoint: http://minio.minio.svc.cluster.local:80
