apiVersion: v1
kind: Secret
metadata:
  name: minio-ak-vm-storage
  namespace: minio
  labels:
    app: minio
    minio-ak-type: user
type: Opaque
stringData:
  accesskey: vm-storage-user
  secretkey: vm-s3k-7c3a1d9e2b5f
  bucket: vm-metrics,vm-logs
  endpoint: http://minio.minio.svc.cluster.local:80
