apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gh-proxy.com/https://github.com/jory-callan/gitops-base
    targetRevision: HEAD
    path: apps/victoria-metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-stack-victoria-metrics-operator-admission
      jsonPointers:
        - /webhooks
    - kind: Secret
      name: victoria-stack-victoria-metrics-operator-validation
