apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-data
  namespace: nfs-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
