apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-storageclass
  labels:
    app: nfs-server
spec:
  type: ClusterIP
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP
  selector:
    app: nfs-server
