apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    # 原始: https://github.com/jory-callan/gitops-base
    # git CLI 通过 insteadOf 走 gh-proxy 代理
    repoURL: https://github.com/jory-callan/gitops-base
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
