apiVersion: v1
kind: ResourceQuota
metadata:
  name: postgres-quota
  namespace: postgres
spec:
  hard:
    requests.memory: 3Gi
    limits.memory: 4Gi
    requests.cpu: 2
    limits.cpu: 4
    persistentvolumeclaims: 6
