apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: nfs-server.nfs-storageclass.svc.cluster.local
          path: /
        storageClass:
          name: nfs-client
          defaultClass: false
          allowVolumeExpansion: true
          reclaimPolicy: Delete
          accessModes: ReadWriteMany
        leaderElection:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-storageclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
