apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kite
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/kite-org/charts
      chart: kite
      targetRevision: 0.12.3
      helm:
        valueFiles:
          - $values/apps/kite/values.yaml
    - repoURL: https://github.com/jory-callan/gitops-base
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/jory-callan/gitops-base
      targetRevision: HEAD
      path: apps/kite
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
