apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  image: 192.168.5.103:5002/minio/minio:RELEASE.2025-09-07T16-13-09Z
  imagePullPolicy: IfNotPresent

  credsSecret:
    name: minio-creds

  pools:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

  mountPath: /export
  subPath: /data
  requestAutoCert: false
  podManagementPolicy: OrderedReady

  # ── Default buckets ─────────────────────────────────────
  buckets:
    - name: velero
      region: us-east-1
    - name: thanos
      region: us-east-1
    - name: loki
      region: us-east-1

  # ── Resource limits ─────────────────────────────────────
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
