apiVersion: v1
kind: ResourceQuota
metadata:
  name: redis-quota
  namespace: redis
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 2Gi
    requests.cpu: 1
    limits.cpu: 3
    persistentvolumeclaims: 3
