apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gitea
    repo: http://192.168.5.103:8081/repository/helm-hosted/
    version: 12.6.0
    releaseName: gitea
    namespace: gitea
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - resourcequota.yaml
